### ISSUE TITLE
credit

### ISSUE THREAD

**Issue by jhaddix** [s0md3v/Parth#5]
If some of the param DB is from the data gathering and parsing I did on HUNT, I'd appreciate a reference =)

**Comment by s0md3v** [comment]
Hi Jhaddix,

These parameters are taken from [GF-Patterns](https://github.com/1ndianl33t/Gf-Patterns) and tweets of [trbughunters](https://twitter.com/trbughunters).
Ideally, I should have credited both of these sources but [according to them](https://twitter.com/s0md3v/status/1296201704610783232), they have compiled it from various sources.  To keep things fair, I just declared this in the README:

```
The database of parameter names and the risks associated with them is mainly created from the public work of various people of the community.
```

With that being said, I am adding your name in the credits section.

Keep building awesome things!
